#
# Wireless Command Station mk. 2
# Nagus
# version 20200211
#

IDF_PATH = $(HOME)/Espressif/esp-idf-release-v4.1

PROJECT_NAME := wics
PROJECT_VER	 := 2.11.001

include $(IDF_PATH)/make/project.mk

